INSERT INTO ShortUrlEntity (hash, target, mode, safe, ip) VALUES ('hhhh', 'target', 1, true, 10.2.3.1)
INSERT INTO ShortUrlEntity (hash, target, mode, safe, ip) VALUES ('aaaa', 'target', 1, true, 10.2.3.1)
INSERT INTO ShortUrlEntity (hash, target, mode, safe, ip) VALUES ('ssss', 'target', 1, true, 10.2.3.1)
INSERT INTO ShortUrlEntity (hash, target, mode, safe, ip) VALUES ('pppp', 'target', 1, true, 10.2.3.1)
INSERT INTO ClickEntity (hash) VALUES ('hhhh')
INSERT INTO ClickEntity (hash) VALUES ('hhhh')
INSERT INTO ClickEntity (hash) VALUES ('hhhh')
INSERT INTO ClickEntity (hash) VALUES ('hhhh')
INSERT INTO ClickEntity (hash) VALUES ('aaaa')
INSERT INTO ClickEntity (hash) VALUES ('aaaa')
INSERT INTO ClickEntity (hash) VALUES ('aaaa')
INSERT INTO ClickEntity (hash) VALUES ('pppp')
INSERT INTO ClickEntity (hash) VALUES ('pppp')
INSERT INTO ClickEntity (hash) VALUES ('pppp')
INSERT INTO ClickEntity (hash) VALUES ('pppp')
INSERT INTO ClickEntity (hash) VALUES ('pppp')
INSERT INTO ClickEntity (hash) VALUES ('ssss')