[versions]
kotlin = "2.4.0"
springBoot = "4.1.0"
springModulith = "2.0.7"
commonsValidator = "1.9.0"
guava = "33.4.8-jre"
kotlinLogging = "7.0.3"
openapi = "3.0.3"
archunit = "1.5.0"
jmolecules = "2025.0.2"
detekt = "1.23.8"
ktlint = "12.2.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
hsqldb = { module = "org.hsqldb:hsqldb" }
postgresql = { module = "org.postgresql:postgresql" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "openapi" }
modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "springModulith" }
modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core" }
modulith-starter-jdbc = { module = "org.springframework.modulith:spring-modulith-starter-jdbc" }
modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
jmolecules-bom = { module = "org.jmolecules:jmolecules-bom", version.ref = "jmolecules" }
jmolecules-hexagonal = { module = "org.jmolecules:jmolecules-hexagonal-architecture" }
jmolecules-archunit = { module = "org.jmolecules.integrations:jmolecules-archunit" }
