# Spring Datasource
spring:
  datasource:
    url: jdbc:hsqldb:mem:.
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /api/metrics