/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package urlshortener.demo.controller;

import urlshortener.demo.domain.QRItem;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-11-23T14:33:33.583Z[GMT]")

@Api(value = "qr", description = "the qr API")
public interface QrApi {

    @ApiOperation(value = "Obtains the QR and the URI associated to a shortened URI", nickname = "getQR", notes = "Obtains the QR and the URI associated to a shortened URI", response = QRItem.class, tags={ "F4 - The app will generate a QR code for every shorthed URI", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "QR and original URI", response = QRItem.class),
        @ApiResponse(code = 404, message = "the shortened URI doesn't exist") })
    @RequestMapping(value = "/qr/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<QRItem> getQR(@ApiParam(value = "",required=true) @PathVariable("id") String id);

}
