/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Stats;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-11-23T14:33:33.583Z[GMT]")

@Api(value = "stats", description = "the stats API")
public interface StatsApi {

    @ApiOperation(value = "Returns stats from server", nickname = "getStats", notes = "Get stats info ", response = Stats.class, tags={ "F1 - The app will return system stats and info. (WS)", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Stats from server", response = Stats.class) })
    @RequestMapping(value = "/stats",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Stats> getStats();

}
