# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: "2.0"
info:
  title: URL SHORTENER
  description: A url shortener is a tool to reduce a long link and then share it.
  version: "1.0.0"
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /api/link:
    post:
      operationId: postlink
      summary: create a shortened URL
      description: Allows a user to create a shortened URL
      parameters: 
        - in: body
          name: URI
          description: The uri to short
          schema:
            type: object
            required:
              - uri
            properties:
              uri:
                type: string
                example: "https://google.com"
              qr:
                type: boolean
                example: "true"
      tags: 
        - Uniform Resource Identifier
      responses:  
        "201":
          description: Application is successfully processed
          headers: 
            Location:
              type: string 
              description: Absolute path to the created trimmed URI
          schema: 
            type: object
            $ref: '#/definitions/shorturl'
        "400":
          description: URI cannot be created
          schema: 
            type: object
            $ref: '#/definitions/Error'
  /api/link/{id}:
    get:
      operationId: getlink
      summary: Information about the URI
      description: Returns relevant information about the shortened URI identified by the parameter id
      parameters:
        - name: id
          in: path
          description: Identifier of the URI
          required: true
          type: string
      tags: 
        - Uniform Resource Identifier
      responses:  
        "200":
          description: Trimmed URI exists and it has been confirmed that it can be used for redirects
          schema:
            type: object
            $ref: '#/definitions/shorturl'
        "400":
          description: Trimmed URI exists and it has not yet been confirmed whether or not the redirection can be made
          schema: 
            type: object
            $ref: '#/definitions/Error'
        "403":
          description: Trimmed URI exists and cannot be used for redirections
          schema: 
            type: object
            $ref: '#/definitions/Error'
        "429":
          description: Shortened URI exists and too many requests have been sent during a given amount of time
          headers:
            Retry-After: 
              type: number
              description: Time in second to wait until next request
          schema: 
            type: object
            $ref: '#/definitions/Error'
  /api/{id}:
    get:
      operationId: redirect
      summary: Get redirect
      description: Performs redirection to a URI identified by the parameter id
      parameters:
        - name: id
          in: path
          description: Identifier of the URI
          required: true
          type: string
      tags: 
        - Uniform Resource Identifier
      responses:  
        "200":
          description: Advertising
          schema:
            type: object
            $ref: '#/definitions/Error'
        "307":
          description: Trimmed URI exists and it has been confirmed that the redirection can be performed
          schema: 
            type: object
            $ref: '#/definitions/Error'
        "400":
          description: Trimmed URI exists and it has not yet been confirmed whether or not the redirection can be made
          headers: 
            Retry-After:
              type: string 
              description: time in seconds until next attempt
          schema: 
            type: object
            $ref: '#/definitions/Error'
        "403":
          description: Trimmed URI exists and cannot be used for redirections
          schema: 
            type: object
            $ref: '#/definitions/Error'
        "429":
          description: Shortened URI exists and too many requests have been sent during a given amount of time
          headers:
            Retry-After: 
              type: number
              description: Time in second to wait until next request
          schema: 
            type: object
            $ref: '#/definitions/Error'
  /api/{id}/qr:
    get:
      operationId: qr
      summary: Get QR
      description: Returns a QR code containing the absolute path of the GET /{id} request.
      parameters:
        - name: id
          in: path
          description: Identifier of the URI
          required: true
          type: string
      tags: 
        - Uniform Resource Identifier
      responses:
        "200":
          description: Trimmed URI exists and it has been confirmed that the redirection can be performed
          headers: 
            Content-Type:
              type: string 
              description: The format used by the QR code must be PNG, SVG or PDF
          schema:
            type: object
            $ref: '#/definitions/Error' 
        "400":
          description: Trimmed URI exists and it has not yet been confirmed whether or not the redirection can be made
          headers: 
            Retry-After:
              type: string 
              description: Time in seconds until next attempt
          schema: 
            type: object
            $ref: '#/definitions/Error'
        "403":
          description: Trimmed URI exists and cannot be used for spam redirects
          schema: 
            type: object
            $ref: '#/definitions/Error'
        "429":
          description: Shortened URI exists and too many requests have been sent during a given amount of time
          headers:
            Retry-After: 
              type: number
              description: time in second to wait until next request
          schema: 
            type: object
            $ref: '#/definitions/Error'
definitions:
  shorturl:
    properties:
      hash:
        type: string
        description: ""
        example: ""
      target:
        type: string
        description: ""
        example: ""
      sponsor:
        type: string
        description: ""
        example: ""
      created:
        type: string
        description: ""
        example: ""
      owner:
        type: string
        description: ""
        example: ""
      mode:
        type: integer
        description: ""
        example: ""
      safe:
        type: boolean
        description: ""
        example: ""
      ip:
        type: string
        description: ""
        example: ""
      lat :
        type: number
        description: ""
        example: ""
      lon :
        type: number
        description: ""
        example: ""
      country:
        type: string
        description: ""
        example: ""
      city:
        type: string
        description: ""
        example: ""
      state:
        type: string
        description: ""
        example: ""
      road:
        type: string
        description: ""
        example: ""
      cp:
        type: string
        description: ""
        example: ""

  click:
    properties:
      id: 
        type: number
        description: ""
        example: ""
      hash: 
        type: string
        description: ""
        example: ""
      created: 
        type: string
        description: ""
        example: ""      
      ip: 
        type: string
        description: ""
        example: ""
      referrer: 
        type: string
        description: ""
        example: ""
      browser: 
        type: string
        description: ""
        example: ""
      platform: 
        type: string
        description: ""
        example: ""
      country: 
        type: string
        description: ""
        example: ""
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string